
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 09 18:42:05 CST 2021
//----------------------------------------------------

package gui.editor;

import java_cup.runtime.Symbol;
import java.util.ArrayList;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Mon Aug 09 18:42:05 CST 2021
  */
public class AnalizadorSintacticoCode extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public AnalizadorSintacticoCode() {super();}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintacticoCode(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintacticoCode(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\012\000\002\002\004\000\002\002\004\000\002\002" +
    "\004\000\002\002\004\000\002\002\004\000\002\002\004" +
    "\000\002\002\004\000\002\002\004\000\002\002\004\000" +
    "\002\002\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\023\000\024\002\ufff8\004\005\005\012\006\013\007" +
    "\007\010\004\011\011\012\010\013\014\001\002\000\024" +
    "\002\ufff8\004\005\005\012\006\013\007\007\010\004\011" +
    "\011\012\010\013\014\001\002\000\024\002\ufff8\004\005" +
    "\005\012\006\013\007\007\010\004\011\011\012\010\013" +
    "\014\001\002\000\004\002\023\001\002\000\024\002\ufff8" +
    "\004\005\005\012\006\013\007\007\010\004\011\011\012" +
    "\010\013\014\001\002\000\024\002\ufff8\004\005\005\012" +
    "\006\013\007\007\010\004\011\011\012\010\013\014\001" +
    "\002\000\024\002\ufff8\004\005\005\012\006\013\007\007" +
    "\010\004\011\011\012\010\013\014\001\002\000\024\002" +
    "\ufff8\004\005\005\012\006\013\007\007\010\004\011\011" +
    "\012\010\013\014\001\002\000\024\002\ufff8\004\005\005" +
    "\012\006\013\007\007\010\004\011\011\012\010\013\014" +
    "\001\002\000\024\002\ufff8\004\005\005\012\006\013\007" +
    "\007\010\004\011\011\012\010\013\014\001\002\000\004" +
    "\002\ufff9\001\002\000\004\002\ufffe\001\002\000\004\002" +
    "\uffff\001\002\000\004\002\ufffb\001\002\000\004\002\ufffa" +
    "\001\002\000\004\002\ufffd\001\002\000\004\002\001\001" +
    "\002\000\004\002\000\001\002\000\004\002\ufffc\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\023\000\004\002\005\001\001\000\004\002\024\001" +
    "\001\000\004\002\023\001\001\000\002\001\001\000\004" +
    "\002\021\001\001\000\004\002\020\001\001\000\004\002" +
    "\017\001\001\000\004\002\016\001\001\000\004\002\015" +
    "\001\001\000\004\002\014\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSintacticoCode$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSintacticoCode$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSintacticoCode$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    //codigo


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AnalizadorSintacticoCode$actions {


    

  private final AnalizadorSintacticoCode parser;

  /** Constructor */
  CUP$AnalizadorSintacticoCode$actions(AnalizadorSintacticoCode parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintacticoCode$do_action(
    int                        CUP$AnalizadorSintacticoCode$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintacticoCode$parser,
    java.util.Stack            CUP$AnalizadorSintacticoCode$stack,
    int                        CUP$AnalizadorSintacticoCode$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalizadorSintacticoCode$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSintacticoCode$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // INICIO ::= 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoCode$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoCode$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // INICIO ::= OTROS INICIO 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoCode$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.elementAt(CUP$AnalizadorSintacticoCode$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoCode$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // INICIO ::= PALABRAS_RESERVADAS INICIO 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoCode$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.elementAt(CUP$AnalizadorSintacticoCode$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoCode$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // INICIO ::= CARACTER INICIO 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoCode$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.elementAt(CUP$AnalizadorSintacticoCode$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoCode$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // INICIO ::= CADENA INICIO 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoCode$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.elementAt(CUP$AnalizadorSintacticoCode$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoCode$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INICIO ::= NUMERO INICIO 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoCode$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.elementAt(CUP$AnalizadorSintacticoCode$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoCode$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // INICIO ::= IDENTIFICADOR INICIO 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoCode$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.elementAt(CUP$AnalizadorSintacticoCode$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoCode$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INICIO ::= COMENTARIO INICIO 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoCode$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.elementAt(CUP$AnalizadorSintacticoCode$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoCode$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= COMENTARIO_SIMPLE INICIO 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoCode$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.elementAt(CUP$AnalizadorSintacticoCode$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoCode$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.elementAt(CUP$AnalizadorSintacticoCode$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.elementAt(CUP$AnalizadorSintacticoCode$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoCode$stack.elementAt(CUP$AnalizadorSintacticoCode$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSintacticoCode$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.elementAt(CUP$AnalizadorSintacticoCode$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoCode$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSintacticoCode$parser.done_parsing();
          return CUP$AnalizadorSintacticoCode$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

