
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 09 18:42:05 CST 2021
//----------------------------------------------------

package gui.editor;

/** CUP generated class containing symbol constants. */
public class SimbolosCode {
  /* terminals */
  public static final int CADENA = 6;
  public static final int COMENTARIO_SIMPLE = 2;
  public static final int EOF = 0;
  public static final int NUMERO = 5;
  public static final int error = 1;
  public static final int PALABRAS_RESERVADAS = 8;
  public static final int OTROS = 9;
  public static final int CARACTER = 7;
  public static final int COMENTARIO = 3;
  public static final int IDENTIFICADOR = 4;
}

