
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 28 18:44:18 CST 2021
//----------------------------------------------------

package backend.analizador;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int IDENTIFICADOR = 3;
  public static final int MENOR_Q = 15;
  public static final int DIVISION = 28;
  public static final int MENOR_IGUAL = 17;
  public static final int CONTINUAR = 59;
  public static final int LA_S = 84;
  public static final int SINO_SI = 85;
  public static final int CARACTER_RSV = 10;
  public static final int MI = 76;
  public static final int RE_S = 81;
  public static final int POTENCIA = 30;
  public static final int MENSAJE = 72;
  public static final int SI = 48;
  public static final int INDENT = 86;
  public static final int SOL = 78;
  public static final int KEEP = 31;
  public static final int SOL_S = 83;
  public static final int DIFERENTE = 13;
  public static final int DEDENT = 87;
  public static final int PRIMOS = 69;
  public static final int POR = 27;
  public static final int NUMERO = 34;
  public static final int PISTA = 2;
  public static final int IGUAL_IGUAL = 12;
  public static final int LONGITUD = 71;
  public static final int PA_C = 51;
  public static final int FALSE = 38;
  public static final int NOT = 24;
  public static final int PA_A = 50;
  public static final int CORCHETE_C = 45;
  public static final int CADENA_RSV = 11;
  public static final int FA = 77;
  public static final int NOR = 22;
  public static final int ORDENAR = 64;
  public static final int CORCHETE_A = 44;
  public static final int VAR = 32;
  public static final int MAYOR_Q = 14;
  public static final int LA = 79;
  public static final int RE = 75;
  public static final int LLAVE_C = 47;
  public static final int LLAVE_A = 46;
  public static final int IMPARES = 68;
  public static final int SALIR = 54;
  public static final int HACER = 58;
  public static final int PUNTO_COMA = 6;
  public static final int PARA = 56;
  public static final int PARES = 67;
  public static final int COMA = 5;
  public static final int DO_S = 80;
  public static final int ENTERO = 7;
  public static final int MODULO = 29;
  public static final int TRUE = 37;
  public static final int DOBLE = 8;
  public static final int IGUAL = 33;
  public static final int DECIMAL = 35;
  public static final int BOOLEAN = 9;
  public static final int SWITCH = 52;
  public static final int DO = 74;
  public static final int VOID = 61;
  public static final int MENOS = 26;
  public static final int MAS = 25;
  public static final int ARREGLO = 43;
  public static final int IS_NULL = 18;
  public static final int EOF = 0;
  public static final int MIENTRAS = 57;
  public static final int DEFAULT = 55;
  public static final int SUMARIZAR = 70;
  public static final int CARACTER = 39;
  public static final int PRINCIPAL = 73;
  public static final int OR = 21;
  public static final int error = 1;
  public static final int REPRODUCIR = 62;
  public static final int SINO = 49;
  public static final int EXTIENDE = 4;
  public static final int CASO = 53;
  public static final int ESPERAR = 63;
  public static final int RETORNAR = 60;
  public static final int CADENA = 36;
  public static final int MAS_MAS = 41;
  public static final int MENOS_MENOS = 42;
  public static final int ASCENDENTE = 65;
  public static final int MAS_IGUAL = 40;
  public static final int FA_S = 82;
  public static final int AND = 19;
  public static final int DESCENDENTE = 66;
  public static final int MAYOR_IGUAL = 16;
  public static final int NAND = 20;
  public static final int XOR = 23;
}

