
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 22 16:47:16 CST 2021
//----------------------------------------------------

package frontend.gui.editor;

/** CUP generated class containing symbol constants. */
public class SimbolosCode {
  /* terminals */
  public static final int IDENTIFICADOR = 5;
  public static final int MENOR_Q = 17;
  public static final int DIVISION = 30;
  public static final int MENOR_IGUAL = 19;
  public static final int CONTINUAR = 61;
  public static final int LA_S = 86;
  public static final int SINO_SI = 87;
  public static final int CARACTER_RSV = 12;
  public static final int MI = 78;
  public static final int RE_S = 83;
  public static final int POTENCIA = 32;
  public static final int MENSAJE = 74;
  public static final int COMENTARIO_LINEA = 2;
  public static final int SI = 50;
  public static final int SOL = 80;
  public static final int KEEP = 33;
  public static final int SOL_S = 85;
  public static final int DIFERENTE = 15;
  public static final int PRIMOS = 71;
  public static final int POR = 29;
  public static final int NUMERO = 36;
  public static final int PISTA = 4;
  public static final int IGUAL_IGUAL = 14;
  public static final int LONGITUD = 73;
  public static final int PA_C = 53;
  public static final int FALSE = 40;
  public static final int NOT = 26;
  public static final int PA_A = 52;
  public static final int CORCHETE_C = 47;
  public static final int CADENA_RSV = 13;
  public static final int FA = 79;
  public static final int NOR = 24;
  public static final int ORDENAR = 66;
  public static final int CORCHETE_A = 46;
  public static final int VAR = 34;
  public static final int MAYOR_Q = 16;
  public static final int LA = 81;
  public static final int RE = 77;
  public static final int LLAVE_C = 49;
  public static final int COMENTARIO_BLOQUE = 3;
  public static final int LLAVE_A = 48;
  public static final int IMPARES = 70;
  public static final int SALIR = 56;
  public static final int HACER = 60;
  public static final int PUNTO_COMA = 8;
  public static final int PARA = 58;
  public static final int PARES = 69;
  public static final int COMA = 7;
  public static final int DO_S = 82;
  public static final int ENTERO = 9;
  public static final int MODULO = 31;
  public static final int TRUE = 39;
  public static final int DOBLE = 10;
  public static final int IGUAL = 35;
  public static final int DECIMAL = 37;
  public static final int BOOLEAN = 11;
  public static final int SWITCH = 54;
  public static final int DO = 76;
  public static final int VOID = 63;
  public static final int MENOS = 28;
  public static final int MAS = 27;
  public static final int ARREGLO = 45;
  public static final int IS_NULL = 20;
  public static final int EOF = 0;
  public static final int MIENTRAS = 59;
  public static final int DEFAULT = 57;
  public static final int SUMARIZAR = 72;
  public static final int CARACTER = 41;
  public static final int PRINCIPAL = 75;
  public static final int OR = 23;
  public static final int error = 1;
  public static final int REPRODUCIR = 64;
  public static final int SINO = 51;
  public static final int EXTIENDE = 6;
  public static final int CASO = 55;
  public static final int ESPERAR = 65;
  public static final int RETORNAR = 62;
  public static final int CADENA = 38;
  public static final int MAS_MAS = 43;
  public static final int MENOS_MENOS = 44;
  public static final int ASCENDENTE = 67;
  public static final int MAS_IGUAL = 42;
  public static final int FA_S = 84;
  public static final int AND = 21;
  public static final int DESCENDENTE = 68;
  public static final int MAYOR_IGUAL = 18;
  public static final int NAND = 22;
  public static final int XOR = 25;
}

